# Project: Hangman Game
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o functions.o
LINKOBJ  = main.o functions.o
LIBS     = -L"F:/Software/Dev-Cpp/TDM-GCC-64/lib" -L"F:/Software/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"F:/Software/Dev-Cpp/TDM-GCC-64/include" -I"F:/Software/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"F:/Software/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"F:/Software/Dev-Cpp/TDM-GCC-64/include" -I"F:/Software/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"F:/Software/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"F:/Software/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Hangman Game.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = F:\Software\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CPP) -c main.c -o main.o $(CXXFLAGS)

functions.o: functions.c
	$(CPP) -c functions.c -o functions.o $(CXXFLAGS)
